{% set name = "xclim" %}
{% set version = "0.47.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e0d084eb900222ae3ba0b09b415f538bc5d712fa5b65708697359cd6ed79c4d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - flit
    - pip
  run:
    - python
    - boltons >=20.1
    - bottleneck >=1.3.1
    - cf_xarray >=0.6.1
    - cftime >=1.4.1
    - click >=8.1
    - dask >=2.6
    - importlib_resources  # [py==38]
    - jsonpickle
    - lmoments3 >=1.0.5
    - numba
    - numpy >=1.16
    - packaging
    - pandas >=0.23,<2.0  # [py==38]
    - pandas >=0.23,<2.2  # [py>=39]
    - pint >=0.10
    - pyyaml
    - scikit-learn >=0.21.3
    - scipy >=1.2
    - statsmodels
    - xarray >=2022.06.0,<2023.11.0

test:
  imports:
    - xclim
    - xclim.ensembles
    - xclim.sdba
  requires:
    - h5netcdf
    - filelock
    - netcdf4
    - pip
    - pooch
    - pytest <8.0
    - pytest-socket
    - pytest-xdist
    - yamale
    - xdoctest
  source_files:
    - tests
    - xclim
  commands:
    - pip check
    - xclim --help  # [not win]
    - xclim --version  # [not win]
    - xclim prefetch_testing_data
    - pytest --numprocesses=auto --dist=loadscope tests -m "not requires_docs"
    - pytest --rootdir=tests --xdoctest xclim

about:
  home: https://github.com/Ouranosinc/xclim
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: An operational Python library supporting climate services, based on xarray
  description: |
    xclim is an operational Python library for climate services, providing numerous
    climate-related indicator tools with an extensible framework for constructing custom
    climate indicators, statistical downscaling and bias adjustment of climate model
    simulations, as well as climate model ensemble analysis tools.
  doc_url: https://xclim.readthedocs.io
  dev_url: https://github.com/Ouranosinc/xclim

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
