{% set name = "xclim" %}
{% set version = "0.56.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36257713271d31ce55cdbc03e285112de60e2bbf313c204605d0ef24c493a740

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.9,<4
    - pip >=25.0
  run:
    - python >={{ python_min }}
    - boltons >=20.1
    - bottleneck >=1.3.1
    - cf_xarray >=0.9.3
    - cftime >=1.4.1
    - click >=8.1
    - dask >=2024.8.1
    - filelock >=3.14.0
    - jsonpickle >=3.1.0
    - numba >=0.57.0
    - numpy >=1.24.0
    - packaging >=24.0
    - pandas >=2.2.0
    - pint >=0.24.4
    - platformdirs >=3.2
    - pyarrow >=15.0.0
    - pyyaml >=6.0.1
    - scikit-learn >=1.2.0
    - scipy >=1.11.0
    - statsmodels >=0.14.2
    - xarray >=2023.11.0,!=2024.10.0
    - yamale >=5.0.0
  run_constrained:
    - fastnanquantile >=0.0.2
    - flox >=0.9
    - lmoments3 >=1.0.7
    - pot >=0.9.4

test:
  imports:
    - xclim
    - xclim.ensembles
    - xclim.sdba
  requires:
    - python {{ python_min }}
    - h5netcdf >=1.3.0
    - pip >=25.0
    - pooch >=1.8.0
    - pytest >=8.0.0
    - pytest-socket >=0.6.0
    - pytest-xdist >=3.2
    - xdoctest >=1.1.5
  source_files:
    - src/xclim
    - tests
  commands:
    - pip check
    - xclim --help
    - xclim --version
    - xclim prefetch_testing_data
    - python -m pytest --numprocesses=auto --dist=loadscope tests -m "not requires_docs" -k "not test_standardized_groundwater_index"
    - python -m pytest --rootdir=tests --xdoctest src/xclim

about:
  home: https://github.com/Ouranosinc/xclim
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: An operational Python library supporting climate services, based on xarray
  description: |
    xclim is an operational Python library for climate services, providing numerous
    climate-related indicator tools with an extensible framework for constructing custom
    climate indicators, statistical downscaling and bias adjustment of climate model
    simulations, as well as climate model ensemble analysis tools.
  doc_url: https://xclim.readthedocs.io
  dev_url: https://github.com/Ouranosinc/xclim

extra:
  recipe-maintainers:
    - aulemahal
    - Zeitsperre
    - huard
